# Generated by Django 4.2.6 on 2024-07-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
