# Generated by Django 4.2.6 on 2024-07-13 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateurs', '0005_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biographie',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_profile',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
