# Generated by Django 4.2.6 on 2024-07-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_alter_profile_biographie_alter_profile_photo_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biographie',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo_profile',
        ),
    ]
