# Generated by Django 4.2.6 on 2024-07-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_userprogress_lesson_complet_delete_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
