# Generated by Django 4.2.6 on 2024-07-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_transaction_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
